name: MonsterParty
main: org.monstercraft.party.MonsterParty
version: '${project.version}'
author: Fletch_to_99
description: A party system.
loadbefore: [Herochat]
commands:
  party:
    description: View party information on out dbo page.
    usage: /party
permissions:
  monsterparty.create:
    description: Create a party.
    default: op
  monsterparty.join:
    description: Join a party.
    default: op
  monsterparty.leave:
    description: leave a party.
    default: op
  monsterparty.teleport:
    description: Teleport to a party member.
    default: op
  monsterparty.*:
    description: All the nodes
    default: op
    children:
      monsterparty.create
      monsterparty.join
      monsterparty.leave
      monsterparty.teleport