name: Parties
main: de.bangl.parties.PartiesPlugin
description: A party system.
version: '${project.version}'

authors: [ Fletch_to_99, Jurre1996, BangL ]

commands:
  p:
    description: Parties main command.
    usage: /<command> (command) (arguments)
    aliases: [ party, parties ]
  pc:
    description: Short of /p chat
    usage: /<command> to toggle party chat mode, or /<command> (message) to send a quick message.
    aliases: [ partychat, partieschat, pchat ]

permissions:
  parties.use:
    description: Allows to use parties.
    default: true
